name: Build I-Pascal

on:
  push:
    branches: [ master, main ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build with Maven (skip tests)
        run: mvn -B -ntp -DskipTests clean package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: i-pascal-artifacts
          if-no-files-found: ignore
          path: |
            plugin/target/*.zip
            plugin/target/*.jar
            jps-plugin/target/*.jar

      # Опционально: создать GitHub Release и приложить артефакты при пуше тега v*
      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            plugin/target/*.zip
            plugin/target/*.jar
            jps-plugin/target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
