# Имя рабочего процесса
name: Build I-Pascal Plugin (for IDEA 2020.1)

# Триггеры для запуска
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build:
    # Запускаем на последней версии Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Устанавливаем JDK 8, так как в pom.xml указана java.version 1.8
      # и целевая IDE 2020.1 работает на Java 8.
      - name: Set up Temurin JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: maven

      # 3. Собираем весь проект с помощью Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # 4. Загружаем ZIP-архив плагина как артефакт
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: i-pascal-plugin-zip
          path: plugin/target/*.zip

      # 5. Публикуем релиз, прикрепляя ZIP-архив (только для события 'release')
      - name: Publish release assets
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: plugin/target/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
